### ISSUE TITLE
The CSS settings of "overflow-*" breaks history navigation for anchors

### ISSUE THREAD

**Issue by eniton** [tomaz/appledoc#214]
It's an annoying behavior to me.

For example, after I click a link in the 'Tasks' section, I can't navigate back to the "Tasks" section by clicking back button of my browser.

I find out that it's caused the CSS settings of #content, after commenting out overflow-x and overflow-y settings in it, history navigation works fine.

``` CSS
#contents, #overview_contents {
    -webkit-overflow-scrolling: touch;
    border-top: 1px solid #2B334F;
    position: absolute;
    top: 91px;
    left: 0;
    right: 0;
    bottom: 0;
    /*overflow-x: hidden;
    overflow-y: auto;*/
    padding-left: 2em;
    padding-right: 2em;
    padding-top: 1em;
    min-width: 550px;
}
```
